package jcbhmr:go-wasi@0.2.7;

world go-wasi {
    include wasi:io/imports@0.2.7;
    include wasi:clocks/imports@0.2.7;
    include wasi:random/imports@0.2.7;
    include wasi:filesystem/imports@0.2.7;
    include wasi:sockets/imports@0.2.7;
    include wasi:cli/imports@0.2.7;
    include wasi:http/imports@0.2.7;
}